In [1]:
import numpy as np
a = np.array([5,5,5,5,5,5,5,5,5])
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5])

In [2]:
type(a)

numpy.ndarray

In [3]:
b=np.array([[5,5,5,5], [5,5,5,5], [5,5,5,5]])
b

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [4]:
type(a)

numpy.ndarray

In [5]:
len(a)

9

In [6]:
a[3]

np.int64(5)

In [9]:
c = np.zeros(2)
c

array([0., 0.])

In [10]:
d = np.empty(3)
d

array([ 1.00132483e-307,  1.61898049e-317, -4.94065646e-324])

In [11]:
e = np.ones(3)
e

array([1., 1., 1.])

In [12]:
f = np.arange(5)
f

array([0, 1, 2, 3, 4])

In [13]:
g = np.arange(5, 15)
g

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
h = np.arange(4, 8, 2)
h

array([4, 6])

In [17]:
i = np.linspace(2,15, num=6)
i

array([ 2. ,  4.6,  7.2,  9.8, 12.4, 15. ])

In [19]:
j = np.ones(5, dtype=np.int8)
j

array([1, 1, 1, 1, 1], dtype=int8)

In [25]:
h = np.ones(3, dtype=np.float64)
h

array([1., 1., 1.])

In [26]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.ones((8,12))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [31]:
np.empty((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
c3d = np.arange(24).reshape(2,3,4)
c3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])