# numpy practice session

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
# import this library in j.notebook
import numpy as np

# Creating an array using numpy

In [3]:
food = np.array(["pakora", "samosa", "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [4]:
price = np.array([5, 5, 5])
price

array([5, 5, 5])

In [5]:
type(price)

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [7]:
len(food)

3

In [8]:
price[2]

np.int64(5)

In [9]:
price[0:]

array([5, 5, 5])

In [10]:
food[1]

np.str_('samosa')

In [11]:
price.mean()

np.float64(5.0)

In [12]:
# Zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [13]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# specify
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [17]:
# Specific interval
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.arange(5, 55, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [20]:
# line space
np.linspace(0, 10, num=8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [22]:
# specify your data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [23]:
# specify your data type
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array functions

In [24]:
a = np.array([10, 12, 15, 2, 41, 65, 54.5, 51.8, 65])
a

array([10. , 12. , 15. ,  2. , 41. , 65. , 54.5, 51.8, 65. ])

In [25]:
a.sort()
a

array([ 2. , 10. , 12. , 15. , 41. , 51.8, 54.5, 65. , 65. ])

In [27]:
b = np.array([10.5, 5, 6.5, 15, 84, 62, 21, 1, 65, 45.5])
b

array([10.5,  5. ,  6.5, 15. , 84. , 62. , 21. ,  1. , 65. , 45.5])

In [31]:
c = np.concatenate((a, b))
c

array([ 2. , 10. , 12. , 15. , 41. , 51.8, 54.5, 65. , 65. , 10.5,  5. ,
        6.5, 15. , 84. , 62. , 21. ,  1. , 65. , 45.5])

In [33]:
c.sort()
c

array([ 1. ,  2. ,  5. ,  6.5, 10. , 10.5, 12. , 15. , 15. , 21. , 41. ,
       45.5, 51.8, 54.5, 62. , 65. , 65. , 65. , 84. ])

# 2-D Arrays

In [43]:
a = np.array([[2, 4],
              [8, 10]])
a

array([[ 2,  4],
       [ 8, 10]])

In [40]:
b = np.array([[6, 7], [8, 9]])
b

array([[6, 7],
       [8, 9]])

In [45]:
c = np.concatenate((a, b), axis=0)
c

array([[ 2,  4],
       [ 8, 10],
       [ 6,  7],
       [ 8,  9]])

In [46]:
c = np.concatenate((a, b), axis=1)
c

array([[ 2,  4,  6,  7],
       [ 8, 10,  8,  9]])

In [47]:
c.ndim

2

In [48]:
c.shape

(2, 4)

In [49]:
a.shape

(2, 2)

In [50]:
b.shape

(2, 2)

In [56]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
b = a.reshape(3, 3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
np.reshape(a, newshape=(1,9), order='c')

C:\Users\hp\AppData\Local\Temp\ipykernel_2320\2416427658.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  np.reshape(a, newshape=(1,9), order='c')


array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [59]:
# convert 1-D to 2-D
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a.shape

(9,)

In [63]:
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [64]:
b.shape

(1, 9)

In [65]:
c = a[: , np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [66]:
a[2:5]

array([3, 4, 5])

In [67]:
b[0:4]

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [68]:
c[1:5]

array([[2],
       [3],
       [4],
       [5]])

In [69]:
a*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [70]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [71]:
a.sum()

np.int64(45)

In [72]:
a.mean()

np.float64(5.0)